# Generated by Django 4.0.3 on 2022-03-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inputs',
            field=models.PositiveIntegerField(default=0, verbose_name='Entradas'),
        ),
        migrations.AddField(
            model_name='product',
            name='outputs',
            field=models.PositiveIntegerField(default=0, verbose_name='Salidas'),
        ),
    ]
