# Generated by Django 3.2.7 on 2021-10-26 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.city', verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.typeofdocument', verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
    ]
