# Generated by Django 3.2.7 on 2021-12-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id_contact'], 'verbose_name': 'Contacto'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='id_Contact',
            new_name='id_contact',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
