# Generated by Django 3.2.7 on 2021-10-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_users_usermodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user_model',
        ),
    ]
