# Generated by Django 4.0.1 on 2022-03-12 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id_accounting_document', models.AutoField(primary_key=True, serialize=False, verbose_name='Id documento contable')),
                ('number_accounting_document', models.CharField(max_length=10, verbose_name='Numero documento contable')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Documento contable',
                'verbose_name_plural': 'Documentos contables',
                'db_table': 'accounting_document',
                'ordering': ['id_accounting_document'],
            },
        ),
    ]
