# Generated by Django 4.0.1 on 2022-03-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_order_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='create',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Creado', 'Creado'), ('Pagado', 'Pagado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Creado', max_length=10, verbose_name='Estado'),
        ),
    ]
