# Generated by Django 4.0.1 on 2022-03-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_accounting_document',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.typeaccountingdocument', verbose_name='Tipo documento contable'),
        ),
    ]
