# Generated by Django 4.0.1 on 2022-03-22 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0003_alter_city_zip_code'),
        ('Orders', '0010_alter_order_shipping_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Creado', 'Creado'), ('Pagado', 'Pagado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Creado', max_length=10, verbose_name=[('Creado', 'Creado'), ('Pagado', 'Pagado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')]),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False, verbose_name='Id direccion')),
                ('address', models.CharField(max_length=70, verbose_name='Direccion')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('default', models.BooleanField(default=False, verbose_name='Direccion principal')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.city', verbose_name='Ciudad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Direccion de envio',
                'verbose_name_plural': 'Direcciones de envio',
                'db_table': 'address',
                'ordering': ['id_address'],
            },
        ),
    ]
