# Generated by Django 4.0.1 on 2022-03-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_usermodel_neighborhood'),
        ('Orders', '0012_address_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.city', verbose_name='Ciudad'),
        ),
    ]
