# Generated by Django 4.0.3 on 2022-03-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.address', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Creado', 'Creado'), ('Pagado', 'Pagado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Creado', max_length=10, verbose_name='Estado'),
        ),
    ]
