# Generated by Django 4.0.3 on 2022-03-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_order_send_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingdocument',
            name='number_accounting_document',
            field=models.CharField(max_length=10, unique=True, verbose_name='Numero documento contable'),
        ),
    ]
