# Generated by Django 4.0.3 on 2022-03-27 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0017_alter_accountingdocument_number_accounting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocument',
            name='accounting_document_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha documento contable'),
            preserve_default=False,
        ),
    ]
