# Generated by Django 4.0.1 on 2022-03-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Carts', '0003_remove_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(through='Carts.CartProducts', to='Products.Product'),
        ),
    ]
