# Generated by Django 4.0.1 on 2022-03-18 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Codigo postal'),
        ),
    ]
