# Generated by Django 4.0.1 on 2022-02-28 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False, verbose_name='Id carrito')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Subtotal')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='Identificador unico')),
                ('product', models.ManyToManyField(to='Products.Product', verbose_name='Productos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito de compras',
                'verbose_name_plural': 'Carritos de compras',
                'db_table': 'cart',
                'ordering': ['id_cart'],
            },
        ),
    ]
