# Generated by Django 4.0.1 on 2022-03-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
