# Generated by Django 4.0.1 on 2022-03-12 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_cart_product'),
        ('Orders', '0002_order_remove_orderdetail_header_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Carts.cart', verbose_name='Carrito'),
            preserve_default=False,
        ),
    ]
