# Generated by Django 4.0.1 on 2022-03-12 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_accountingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_total',
            field=models.PositiveIntegerField(default=5000, verbose_name='Costo envio'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
