# Generated by Django 4.0.1 on 2022-03-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_create_order_modified_order_shipping_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.paymenttype', verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_accounting_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.typeaccountingdocument', verbose_name='Tipo documento contable'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.typeofdelivery', verbose_name='Tipo de entrega'),
        ),
    ]
