# Generated by Django 4.0.1 on 2022-03-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_remove_order_create_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='identifier',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Identificador unico'),
            preserve_default=False,
        ),
    ]
