# Generated by Django 4.0.1 on 2022-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_alter_order_state_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(default=' ', max_length=50, verbose_name='Barrio/Localidad'),
            preserve_default=False,
        ),
    ]
