# Generated by Django 4.0.3 on 2022-03-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_order_address_alter_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
