# Generated by Django 4.0.3 on 2022-03-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_accountingdocument_accounting_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingdocument',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Orders.order', verbose_name='Orden'),
        ),
    ]
